"""empty message

Revision ID: c0223ac8deac
Revises: 
Create Date: 2026-05-16 19:05:14.151397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c0223ac8deac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educationmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('okul_adi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bolum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('baslangic_yili', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mezuniyet_yili', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detay', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sirket_adi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pozisyon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aciklama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiencemodel')
    op.drop_table('educationmodel')
    # ### end Alembic commands ###
